import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Button, Container, ThemeProvider, createTheme } from "@mui/material";

import "./globals.scss";
import Header from "./header";
import { theme } from "../themes/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <main>
            <Header />
            <Container maxWidth="lg">{children}</Container>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
